# This is a basic workflow to help you get started with Actions

name: PP Secret Scanning

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Initial Env
        run: |
          rm -rf *
          rm -rf .git
          ls -a
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: SecretScanning
        run: |
          brew install git-secrets
          git secrets --install -f
          git secrets --register-aws
          git secrets --add --allowed .github/workflows/*.yml:.*
          git secrets --add --global '[A-Z0-9]{1}'
          git secrets --scan && echo $?
        
#       - name: SecretScanning
#         uses: PPLoading/PPLoading-action@v2
#         with:
#           secretId: ${{ secrets.SECRETID }}
#           secretKey: ${{ secrets.SECRETKEY }}
#           envId: ${{ secrets.ENVID }}
#           include_path: 'configuration/include_paths.txt'
#           exclude_path: 'configuration/exclude_paths.txt'
